spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account_app?ApplicationName=TestSweetApp
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20 # Увеличить при необходимости
      leak-detection-threshold: 60000  # Включить детектор утечек
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


classifier_currency_url: http://localhost:8081/api/v1/classifier/currency/
classifier_category_url: http://localhost:8081/api/v1/classifier/operation/category/
encryption_url: http://localhost:8084/api/v1/encryption/